### ISSUE TITLE
Restricted Access to Search Engines

### ISSUE THREAD

**Issue by hcgraf** [CyanogenMod/android_packages_apps_Gello#1]
Hi.

I'm using CM13 and and got in touch with Gello with on of the latest Nightlies.
It seems to be a very nice browser, congratulations & thanks for your effort!

However, I would like to be able to set DuckDuckGo as my search engine, which didn't seem to be possible.
After some investigation, I found out that you have a really impressive set of search engines configured in  `res/values/all_search_engines.xml`.
Unfortunately, the list of engines is limited depending on the language/region to just a few, e.g. in  `res/values-de-rDE/donottranslate-search_engines.xml`.
These region specific lists are generated by `tools/get_search_engines.py` which seems to be outdated (the downloaded chromium source file doesn't exist anymore).

And here is my question:
Why don't you allow the user to select from the entire list of search engines? Even for the search engines with several variants (Google, Yahoo, etc.) some people might prefer using the "global" (english) instead of the localized variant.
Especially for a browser which aims to be "customizable", I think having a big list of search engines would be a plus!

Please share your thoughts :)

**Comment by github-cygwin** [comment]
I second this request.  Please allow the user to use any search engine.  Just because a user is based in some country doesn't mean she's using the language setup of this country.  Personally I'm german but using English as UI language as on all my machines.  But of course I'd like to be able to use a german or EU-based search engine of choice, e.g. DuckDuckGo, IXQuick, or Startpage.
So, please allow the user to use all preconfigured search engines, and also to define additional search engines, like Firefox does.


Thanks,
Corinna

**Comment by hcgraf** [comment]
I provided a possible solution in PR #4 
I'm sorry I did not use Gerrit to suggest this change, but I don't want to setup the entire Cyanogenmod Build Environment just to submit a very small change to Gello (I don't even have enough free space for that atm)..

If it is possible to submit to Gerrit without setting up the whole CM-Stuff, I would be happy to do so.
(Please point me to the relevant docs!)

**Comment by github-cygwin** [comment]
On Jun  1 01:15, Hagen Graf wrote:
> I provided a possible solution in PR #4 
> I'm sorry I did not use Gerrit to suggest this change, but I don't want to setup the entire Cyanogenmod Build Environment just to submit a very small change to Gello (I don't even have enough free space for that atm)..
> 
> If it is possible to submit to Gerrit without setting up the whole CM-Stuff, I would be happy to do so.
> (Please point me to the relevant docs!)

Does http://review.cyanogenmod.org/Documentation/user-upload.html help?
It explains the process quite nicely, IMHO.


Corinna

**Comment by hcgraf** [comment]
Thanks. That actually helped. 

Here is the patch to review: http://review.cyanogenmod.org/#/c/147304/

**Comment by hcgraf** [comment]
Merged into the next nightly. Closing.
